Update bluetooth.h
*****need to solve  undefined reference to Comm::Listener****
use member initialization list; 
declare bluetooth destrustor to solve undefined reference to Comm::~Comm(), vtable for bluetooth;
implement SendFirst virtual function